### ISSUE TITLE
can't create browser object for phantomjs

### ISSUE THREAD

**Issue by bmiller-fiksu** [watir/watir#222]
```
$ irb
irb(main):001:0>
irb(main):002:0*
irb(main):003:0* require 'watir-webdriver'
=> true
irb(main):004:0> browser = Watir::Browser.new :phantomjs
Selenium::WebDriver::Error::WebDriverError: unable to connect to phantomjs @ http://127.0.0.1:8910 after 20 seconds
    from /Users/bmiller/.rvm/gems/ruby-1.9.3-p327/gems/selenium-webdriver-2.35.1/lib/selenium/webdriver/phantomjs/service.rb:47:in `start'
    from /Users/bmiller/.rvm/gems/ruby-1.9.3-p327/gems/selenium-webdriver-2.35.1/lib/selenium/webdriver/phantomjs/bridge.rb:20:in `initialize'
    from /Users/bmiller/.rvm/gems/ruby-1.9.3-p327/gems/selenium-webdriver-2.35.1/lib/selenium/webdriver/common/driver.rb:45:in `new'
    from /Users/bmiller/.rvm/gems/ruby-1.9.3-p327/gems/selenium-webdriver-2.35.1/lib/selenium/webdriver/common/driver.rb:45:in `for'
    from /Users/bmiller/.rvm/gems/ruby-1.9.3-p327/gems/selenium-webdriver-2.35.1/lib/selenium/webdriver.rb:67:in `for'
    from /Users/bmiller/.rvm/gems/ruby-1.9.3-p327/gems/watir-webdriver-0.6.4/lib/watir-webdriver/browser.rb:46:in `initialize'
    from (irb):4:in `new'
    from (irb):4
    from /Users/bmiller/.rvm/rubies/ruby-1.9.3-p327/bin/irb:18:in `<main>'
```

watir-webdriver version 0.6.2
selenium-webdriver version 2.29.0

**Comment by mada41** [comment]
thanks for share your solution @raphox , you save my life :smile:
