### ISSUE TITLE
Chromedriver switches generating argument error in Selenium 3.0.0.beta4

### ISSUE THREAD

**Issue by azohra** [watir/watir#481]
Hey folks, 

I am unsure if this fix will be in Watir or Selenium, but we are seeing a new error with the latest Selenium 3.0 beta4 release when using switches + chrome. When we switch back down to beta3, the error no longer occurs.

Any thoughts? 

``` ruby
browser = Watir::Browser.new :chrome, switches: %w[--allow-running-insecure-content --ignore-certificate-errors --ignore-urlfetcher-cert-requests --disable-gpu --no-sandbox], prefs: { profile: { managed_default_content_settings: { geolocation: 2 }, password_manager_enabled: false } }
```

`````` bash
unknown option: {:switches=>["--allow-running-insecure-content", "--ignore-certificate-errors", "--ignore-urlfetcher-cert-requests", "--disable-gpu", "--no-sandbox"]} (ArgumentError)
/Users/fbarann/.gem/ruby/2.3.1/gems/selenium-webdriver-3.0.0.beta4.0/lib/selenium/webdriver/remote/bridge.rb:71:in `initialize'
/Users/fbarann/.gem/ruby/2.3.1/gems/selenium-webdriver-3.0.0.beta4.0/lib/selenium/webdriver/chrome/bridge.rb:40:in `initialize'
/Users/fbarann/.gem/ruby/2.3.1/gems/selenium-webdriver-3.0.0.beta4.0/lib/selenium/webdriver/common/driver.rb:62:in `new'
/Users/fbarann/.gem/ruby/2.3.1/gems/selenium-webdriver-3.0.0.beta4.0/lib/selenium/webdriver/common/driver.rb:62:in `for'
/Users/fbarann/.gem/ruby/2.3.1/gems/selenium-webdriver-3.0.0.beta4.0/lib/selenium/webdriver.rb:82:in `for'
/Users/fbarann/.gem/ruby/2.3.1/gems/watir-6.0.0.beta5/lib/watir/browser.rb:46:in `initialize'
/Users/fbarann/Work/bueller_cc/features/support/env.rb:100:in `new'
/Users/fbarann/Work/bueller_cc/features/support/env.rb:100:in `<top (required)>'
/Users/fbarann/.gem/ruby/2.3.1/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load'
/Users/fbarann/.gem/ruby/2.3.1/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load_code_file'
/Users/fbarann/.gem/ruby/2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:142:in `load_file'
/Users/fbarann/.gem/ruby/2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:84:in `block in load_files!'
/Users/fbarann/.gem/ruby/2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `each'
/Users/fbarann/.gem/ruby/2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `load_files!'
/Users/fbarann/.gem/ruby/2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:253:in `load_step_definitions'
/Users/fbarann/.gem/ruby/2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:61:in `run!'
/Users/fbarann/.gem/ruby/2.3.1/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
/Users/fbarann/.gem/ruby/2.3.1/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
/Users/fbarann/.gem/ruby/2.3.1/bin/cucumber:23:in `load'
/Users/fbarann/.gem/ruby/2.3.1/bin/cucumber:23:in `<top (required)>'
/Users/fbarann/.gem/ruby/2.3.1/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:74:in `load'
/Users/fbarann/.gem/ruby/2.3.1/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/fbarann/.gem/ruby/2.3.1/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:27:in `run'
/Users/fbarann/.gem/ruby/2.3.1/gems/bundler-1.13.1/lib/bundler/cli.rb:332:in `exec'
/Users/fbarann/.gem/ruby/2.3.1/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/fbarann/.gem/ruby/2.3.1/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/fbarann/.gem/ruby/2.3.1/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/fbarann/.gem/ruby/2.3.1/gems/bundler-1.13.1/lib/bundler/cli.rb:20:in `dispatch'
/Users/fbarann/.gem/ruby/2.3.1/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/fbarann/.gem/ruby/2.3.1/gems/bundler-1.13.1/lib/bundler/cli.rb:11:in `start'
/Users/fbarann/.gem/ruby/2.3.1/gems/bundler-1.13.1/exe/bundle:34:in `block in <top (required)>'
/Users/fbarann/.gem/ruby/2.3.1/gems/bundler-1.13.1/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/Users/fbarann/.gem/ruby/2.3.1/gems/bundler-1.13.1/exe/bundle:26:in `<top (required)>'
/Users/fbarann/.gem/ruby/2.3.1/bin/bundle:23:in `load'
/Users/fbarann/.gem/ruby/2.3.1/bin/bundle:23:in `<main>'```
``````

**Comment by titusfortner** [comment]
This is technically a Selenium bug, but I'm the one who broke it, so I'll figure out the fix. It was all supposed to be backward compatible. Thanks for testing it and reporting it.

**Comment by titusfortner** [comment]
Fixed: https://github.com/SeleniumHQ/selenium/commit/b07794e18c003d57dffeb8fa3a0764dd2c2ce37f

**Comment by azohra** [comment]
Cheers :)
