### ISSUE TITLE
cannot load such file -- watir (LoadError) when running rspec

### ISSUE THREAD

**Issue by mcshakes** [watir/watir#529]
Whenever I try and run rspec, I get this error:

```
/spec/spec_helper.rb:2:in `require': cannot load such file -- watir (LoadError)
	from /Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `load'
	from /Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
	from /Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `each'
	from /Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
	from /Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:97:in `setup'
	from /Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:85:in `run'
	from /Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
	from /Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
	from /Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.2.3/exe/rspec:4:in `<top (required)>'
	from /Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0/bin/rspec:22:in `load'
	from /Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0/bin/rspec:22:in `<main>'
	from /Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

My spec_helper.rb:

require 'watir'
require 'watir-scroll'
require 'rspec'
require 'yaml'
require 'open-uri'
require 'rspec_junit_formatter'
require 'watir-webdriver-performance'

My system:

ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin14]
rvm 1.28.0 (latest)

After gem list (abbreviated for related gems) :

```selenium-webdriver (3.0.5)
watir (6.1.0)
watir-scroll (0.3.0, 0.1.0)
watir-webdriver (0.9.9)
watir-webdriver-performance (0.2.4)
```

Am I missing something here in the dependency?

**Comment by p0deje** [comment]
No, it seems to be correct, can it be that you run it somehow without gems loading?

If you remove `require 'watir'` does it work for other gems?

**Comment by mcshakes** [comment]
@p0deje So, I commented out `require 'watir'`  and `require 'watir-scroll'` and it does seem to work for other gems, notably rspec (all the specs failed, but it was being loaded)

- When I uncomment `require 'watir-scroll'` and re-run rspec, I get a bunch of these errors:

```/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:17: warning: constant ::Fixnum is deprecated
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:137: warning: constant ::Fixnum is deprecated
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:138: warning: constant ::Fixnum is deprecated
```

(it goes on and on)

- One workaround I have gotten to do is to `rvm use ruby 2.1.4` (This is the older version I have). I then run rspec with my spec_helper.rb looking like this:

```# require 'watir'
require 'watir-scroll'
require 'rspec'
require 'yaml'
require 'open-uri'
require 'rspec_junit_formatter'
require 'watir-webdriver-performance'
```

(notice the require 'watir' is commented out)

The specs run successfully with no issue. If I uncomment `require 'watir'` and run spec, I get the same error as my initial issue:

```/Users/EdwardMcCarthy/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- watir/loader (LoadError)```

**NOTE: I can also use `require 'watir-webdriver'` and get the deprecation warning**

The main problem with using Ruby 2.1.4 is when I try to bundle and get SSL Certificate errors (the reason I updated to Ruby 2.4)

**Comment by p0deje** [comment]
It seems to me that something is wrong with your rubygems in general. Can you try to reproduce the bug on a fresh Ruby installation with a new RVM gemset? Or maybe switch to Bundler?

it's very hard to debug that kind of issues. If you can create a reproducible test case (e.g. with clean RVM ruby + gemset), it'd be helpful.

**Comment by mcshakes** [comment]
Alright, my steps:

1) rvm remove 2.4.0
2) rvm install ruby-2.4.0
3) gem update --system
4) rvm gemset use global
5) gem install bundler
6) gem install watir --no-ri --no-rdoc
7) gem install rspec --no-ri --no-rdoc
8) Added chromedriver.exe and geckodriver.exe to the /Users/USERNAME/.rvm/rubies/ruby-2.4.0/bin
9) bundle installed

- I go this message

```
With the release of Watir 6.0, the watir-webdriver gem has changed its name
to watir. Update your dependencies to use "watir", "~> 6.0"
```

Afterwards, rspec worked. Don't know what to tell you. I will close this issue. Thank you

**Comment by titusfortner** [comment]
I would have said the issue was `watir-webdriver-performance` requiring `watir-webdriver` instead of just `watir`. Looks like that project has an open issue, but hasn't done anything with it. I don't understand their versioning craziness in their gem file so I didn't know how to PR the change. 

Glad you got this working for you.

**Comment by mcshakes** [comment]
@titusfortner Not so sure whether `watir-webdriver-performance` is causing anything (yet). Have had multiple clean runs with is since then on my local with `watir-webdriver-performance` required. Strangely, requiring `watir-scroll` gives me some new bunch of errors to deal with:

```
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/wait.rb:9: warning: already initialized constant Watir::Wait::INTERVAL
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-6.1.0/lib/watir/wait.rb:8: warning: previous definition of INTERVAL was here
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/atoms.rb:4: warning: already initialized constant Watir::Atoms::ATOMS
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-6.1.0/lib/watir/atoms.rb:4: warning: previous definition of ATOMS was here
```

Oh well. On to this next batch then

**Comment by titusfortner** [comment]
yeah, you are requiring both `watir` & `watir-webdriver` which you shouldn't do.
If you just require `watir` and don't require `watir-webdriver-performance` what happens?

**Comment by mcshakes** [comment]
Oh, no. Currently, I'm requiring just these:

```
require 'watir'
require 'watir-scroll'
require 'rspec'
require 'yaml'
require 'open-uri'
require 'rspec_junit_formatter'
```
Full errors:

```
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/wait.rb:9: warning: already initialized constant Watir::Wait::INTERVAL
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-6.1.0/lib/watir/wait.rb:8: warning: previous definition of INTERVAL was here
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/atoms.rb:4: warning: already initialized constant Watir::Atoms::ATOMS
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-6.1.0/lib/watir/atoms.rb:4: warning: previous definition of ATOMS was here
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:17: warning: constant ::Fixnum is deprecated
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:137: warning: constant ::Fixnum is deprecated
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:138: warning: constant ::Fixnum is deprecated
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:139: warning: constant ::Fixnum is deprecated
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:140: warning: constant ::Fixnum is deprecated
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:142: warning: constant ::Fixnum is deprecated
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:158: warning: constant ::Fixnum is deprecated
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:161: warning: constant ::Fixnum is deprecated
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:168: warning: constant ::Fixnum is deprecated
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:169: warning: constant ::Fixnum is deprecated
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:301: warning: constant ::Fixnum is deprecated
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:306: warning: constant ::Fixnum is deprecated
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:307: warning: constant ::Fixnum is deprecated
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:316: warning: constant ::Fixnum is deprecated
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:321: warning: constant ::Fixnum is deprecated
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:322: warning: constant ::Fixnum is deprecated
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:335: warning: constant ::Fixnum is deprecated
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:361: warning: constant ::Fixnum is deprecated
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:364: warning: constant ::Fixnum is deprecated
/Users/EdwardMcCarthy/.rvm/gems/ruby-2.4.0@global/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/html_elements.rb:366: warning: constant ::Fixnum is deprecated```

**Comment by titusfortner** [comment]
check your `Gemfile.lock` then, something is requiring `watir-webdriver` that you don't want.

**Comment by mcshakes** [comment]
@titusfortner Thanks for the heads up. Fixed it by commenting out `require 'watir-webdriver-performance'`, and using 0.3.0 for watir-scroll (seems like 0.1.0 kept trying to revert to watir-webdriver. Gemfile.lock now looks like this:

```
  watir (6.1.0)
      selenium-webdriver (~> 3.0)
    watir-scroll (0.3.0)
      watir (>= 6.0)
```

**Comment by titusfortner** [comment]
Great, glad it is working. 

These issues are letting me know about a number of Watir add-on gems that I'd not heard of before. :)
