### ISSUE TITLE
GOTO Results in Unknown Error

### ISSUE THREAD

**Issue by gavk34** [watir/watir#549]
Seeing the following issue when attempting to use goto for FF

Versions:
Watir: 6.2.1
Selenium: 3.3
FF: 53.0b9
Geckodriver: 0.15.0

```
 prof = Selenium::WebDriver::Firefox::Profile.new
    prof['app.update.auto']=false
    prof['app.update.enabled']=false
    prof['browser.search.update']=false
    prof['extensions.update.enabled']=false
    prof['browser.download.folderList'] = 2 # custom location
    prof['browser.helperApps.neverAsk.saveToDisk'] = "text/csv,application/pdf,application/samlmetadata+xml,text/calendar,image/png"
    browser = Watir::Browser.new :firefox, :profile => prof
    browser.window.resize_to(1580, 1024)
    browser.goto 'www.google.com'
```

> Selenium::WebDriver::Error::UnknownError: Exception
>   Stack Trace:
>   /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
>   /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
>   /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
>   /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
>   /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
>   /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
>   /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/w3c_bridge.rb:620:in `execute'
>   /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/w3c_bridge.rb:126:in `get'
>   /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/common/navigation.rb:32:in `to'
>   /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.2.1/lib/watir/browser.rb:78:in `goto'
>   /tests/pages/Login/LoginPage.rb:30:in `initialize'
>   /tests/helpers/login_helper.rb:18:in `new'
>   /tests/helpers/login_helper.rb:18:in `login_as_user'
>   /tests/synthetic/login_tests.rb:21:in `test_that_a_regular_user_can_login

**Comment by gavk34** [comment]
Sorry, there was missing additional logic that was causing this - closing
https://github.com/mozilla/geckodriver/issues/93
