### ISSUE TITLE
Net::ReadTimeout when attempting to switch to a new window.

### ISSUE THREAD

**Issue by kapoorlakshya** [watir/watir#573]
The application I am testing displays its exception and stack trace messages in a new browser window with the url as `about:blank` and the window title is the URL where the application is hosted. This page only contains JSON:

```
{"0":"Object doesn't support property or method 'initKeyEvent'","1":"","2":28,"3":201,"4":{"description":"Object doesn't support property or method 'initKeyEvent'","number":-2146827850,"stack":"TypeError: Object doesn't support property or method 'initKeyEvent'\n   at W (Unknown script code:28:201)\n   at na (Unknown script code:29:469)\n   at Anonymous function (Unknown script code:29:903)\n   at Anonymous function (Unknown script code:15:12)\n   at Anonymous function (Unknown script code:1:73)"}}          
```

`@browser.windows.count` returns 2 which confirms that Watir detects the new window. However, when I try to use it with `@browser.windows.last.use` it times out with `Net::ReadTimeout`. It even times out if I try to get the URL for that window:

```
[5] pry(#<Actions>)> @browser.windows
=> [
    [0] #<Watir::Window:0x..fe5ddb72c located=true>,
    [1] #<Watir::Window:0x..fb5554b4 located=true>
]
[6] pry(#<Actions>)> @browser.windows[1].url
Net::ReadTimeout: Net::ReadTimeout
from I:/Opt/Ruby/Ruby223x64/lib/ruby/2.3.0/net/protocol.rb:158:in `rbuf_fill'
[7] pry(#<CaActions>)>
```

I am able to interact with other windows without a problem, but not with this specific window. Any idea why? I am using Watir 6.3.0 and Selenium 3.4.3.

**Comment by titusfortner** [comment]
I'm assuming this is an IE-only thing and so you can't verify it working or not working using Chrome?

Net::ReadTimeout errors usually mean that the driver is not returning a response from the command sent to it. Are you using the most recent 32 bit version of the IEDriverServer?

Add `Selenium::WebDriver.logger.level = :info` before your code and re-run. If there is a command being sent to the window endpoint that isn't returning a value, then this is an IEDriver bug, and needs to be filed in the Selenium project along with the applicable details from the logger.

**Comment by kapoorlakshya** [comment]
Right after I left my comment, I realized I should test this with Chrome. Unfortunately, Chrome has the same behavior except for when switching windows with `#use`. Here is the log for Chrome with `:info` logging:

```
[1] pry(#<Actions>)> @browser.windows
2017-07-06 15:40:54 INFO Selenium -> GET session/6750a364b7b8e6aead00b725db1a80d3/window_handles
2017-07-06 15:40:54 INFO Selenium <- {"sessionId":"6750a364b7b8e6aead00b725db1a80d3","status":0,"value":["CDwindow-7fbd69fa-0cd9-456e-9df4-d626c3476876","CDwindow-5e53fc69-b69e-4f31-8e25-9072cf0156cb"]}
=> [
    [0] #<Watir::Window:0x..f561593ee located=true>,
    [1] #<Watir::Window:0x76398d14 located=true>
]
[2] pry(#<Actions>)> @browser.windows[0].current?
2017-07-06 15:41:02 INFO Selenium -> GET session/6750a364b7b8e6aead00b725db1a80d3/window_handles
2017-07-06 15:41:02 INFO Selenium <- {"sessionId":"6750a364b7b8e6aead00b725db1a80d3","status":0,"value":["CDwindow-7fbd69fa-0cd9-456e-9df4-d626c3476876","CDwindow-5e53fc69-b69e-4f31-8e25-9072cf0156cb"]}
2017-07-06 15:41:02 INFO Selenium -> GET session/6750a364b7b8e6aead00b725db1a80d3/window_handle
2017-07-06 15:41:02 INFO Selenium <- {"sessionId":"6750a364b7b8e6aead00b725db1a80d3","status":0,"value":"CDwindow-7fbd69fa-0cd9-456e-9df4-d626c3476876"}
=> true
[3] pry(#<Actions>)> @browser.windows.last.use
2017-07-06 15:41:08 INFO Selenium -> GET session/6750a364b7b8e6aead00b725db1a80d3/window_handles
2017-07-06 15:41:08 INFO Selenium <- {"sessionId":"6750a364b7b8e6aead00b725db1a80d3","status":0,"value":["CDwindow-7fbd69fa-0cd9-456e-9df4-d626c3476876","CDwindow-5e53fc69-b69e-4f31-8e25-9072cf0156cb"]}
2017-07-06 15:41:08 INFO Selenium -> GET session/6750a364b7b8e6aead00b725db1a80d3/window_handles
2017-07-06 15:41:08 INFO Selenium <- {"sessionId":"6750a364b7b8e6aead00b725db1a80d3","status":0,"value":["CDwindow-7fbd69fa-0cd9-456e-9df4-d626c3476876","CDwindow-5e53fc69-b69e-4f31-8e25-9072cf0156cb"]}
2017-07-06 15:41:08 INFO Selenium -> POST session/6750a364b7b8e6aead00b725db1a80d3/window
2017-07-06 15:41:08 INFO Selenium    >>> http://127.0.0.1:9515/session/6750a364b7b8e6aead00b725db1a80d3/window | {"name":"CDwindow-5e53fc69-b69e-4f31-8e25-9072cf0156cb"}
2017-07-06 15:41:08 INFO Selenium <- {"sessionId":"6750a364b7b8e6aead00b725db1a80d3","status":0,"value":null}

=> #<Watir::Window:0x76398d14 located=true>
[4] pry(#<Actions>)> @browser.windows[1].current?
2017-07-06 15:41:11 INFO Selenium -> GET session/6750a364b7b8e6aead00b725db1a80d3/window_handles
2017-07-06 15:41:11 INFO Selenium <- {"sessionId":"6750a364b7b8e6aead00b725db1a80d3","status":0,"value":["CDwindow-7fbd69fa-0cd9-456e-9df4-d626c3476876","CDwindow-5e53fc69-b69e-4f31-8e25-9072cf0156cb"]}
2017-07-06 15:41:11 INFO Selenium -> GET session/6750a364b7b8e6aead00b725db1a80d3/window_handle
2017-07-06 15:41:11 INFO Selenium <- {"sessionId":"6750a364b7b8e6aead00b725db1a80d3","status":0,"value":"CDwindow-5e53fc69-b69e-4f31-8e25-9072cf0156cb"}
=> true
[5] pry(#<Actions>)> @browser.windows[1].url
2017-07-06 15:41:16 INFO Selenium -> GET session/6750a364b7b8e6aead00b725db1a80d3/window_handles
2017-07-06 15:41:16 INFO Selenium <- {"sessionId":"6750a364b7b8e6aead00b725db1a80d3","status":0,"value":["CDwindow-7fbd69fa-0cd9-456e-9df4-d626c3476876","CDwindow-5e53fc69-b69e-4f31-8e25-9072cf0156cb"]}
2017-07-06 15:41:16 INFO Selenium -> GET session/6750a364b7b8e6aead00b725db1a80d3/window_handles
2017-07-06 15:41:16 INFO Selenium <- {"sessionId":"6750a364b7b8e6aead00b725db1a80d3","status":0,"value":["CDwindow-7fbd69fa-0cd9-456e-9df4-d626c3476876","CDwindow-5e53fc69-b69e-4f31-8e25-9072cf0156cb"]}
2017-07-06 15:41:16 INFO Selenium -> GET session/6750a364b7b8e6aead00b725db1a80d3/window_handle
2017-07-06 15:41:16 INFO Selenium <- {"sessionId":"6750a364b7b8e6aead00b725db1a80d3","status":0,"value":"CDwindow-5e53fc69-b69e-4f31-8e25-9072cf0156cb"}
2017-07-06 15:41:16 INFO Selenium -> GET session/6750a364b7b8e6aead00b725db1a80d3/window_handles
2017-07-06 15:41:16 INFO Selenium <- {"sessionId":"6750a364b7b8e6aead00b725db1a80d3","status":0,"value":["CDwindow-7fbd69fa-0cd9-456e-9df4-d626c3476876","CDwindow-5e53fc69-b69e-4f31-8e25-9072cf0156cb"]}
2017-07-06 15:41:16 INFO Selenium -> POST session/6750a364b7b8e6aead00b725db1a80d3/window
2017-07-06 15:41:16 INFO Selenium    >>> http://127.0.0.1:9515/session/6750a364b7b8e6aead00b725db1a80d3/window | {"name":"CDwindow-5e53fc69-b69e-4f31-8e25-9072cf0156cb"}
2017-07-06 15:41:16 INFO Selenium <- {"sessionId":"6750a364b7b8e6aead00b725db1a80d3","status":0,"value":null}

2017-07-06 15:41:16 INFO Selenium -> GET session/6750a364b7b8e6aead00b725db1a80d3/url
2017-07-06 15:43:16 INFO Selenium -> GET session/6750a364b7b8e6aead00b725db1a80d3/window_handles
Net::ReadTimeout: Net::ReadTimeout
from I:/Opt/Ruby/Ruby223x64/lib/ruby/2.3.0/net/protocol.rb:158:in `rbuf_fill'
[6] pry(#<CaActions>)> @browser.url
2017-07-06 15:47:17 INFO Selenium -> GET session/6750a364b7b8e6aead00b725db1a80d3/window_handle
Net::ReadTimeout: Net::ReadTimeout
from I:/Opt/Ruby/Ruby223x64/lib/ruby/2.3.0/net/protocol.rb:158:in `rbuf_fill'
[7] pry(#<CaActions>)>
```

Updated the title to remove 'IE' since I have reproduced it in Chrome.

**Comment by titusfortner** [comment]
Did `GET session/6750a364b7b8e6aead00b725db1a80d3/url` not return a value?

Are you saying IE & Chrome have this exact same behavior? Or the same error is thrown in different places?

Out of curiosity, what does it look like if you use `gem "watir", ">= 6.4.0.rc2"`?

**Comment by kapoorlakshya** [comment]
No, it did not return a value. I am saying that I am getting the same `Net::ReadTimeout: Net::ReadTimeout` in both IE and Chrome when I try to retrieve the URL or title for the new window.

I tested this using v6.4.0.rc2 - in IE, it times out when I attempt to switch windows with `#use`:

```
[1] pry(#<CaActions>)> @browser.windows
2017-07-06 23:17:23 INFO Selenium -> GET session/85c17f0b-e6aa-480a-a98e-92584475a54a/window_handles
2017-07-06 23:17:23 INFO Selenium <- {"sessionId":"85c17f0b-e6aa-480a-a98e-92584475a54a","status":0,"value":["a2658638-9fe8-425c-924a-c2aba86b9341","4138b533-381a-4239-82d8-b29aa402786c"]}
=> [
    [0] #<Watir::Window:0x..febe03690 located=true>,
    [1] #<Watir::Window:0x1c9ff3ca located=true>
]
[2] pry(#<Actions>)> @browser.windows.last.use
2017-07-06 23:17:27 INFO Selenium -> GET session/85c17f0b-e6aa-480a-a98e-92584475a54a/window_handles
2017-07-06 23:17:27 INFO Selenium <- {"sessionId":"85c17f0b-e6aa-480a-a98e-92584475a54a","status":0,"value":["a2658638-9fe8-425c-924a-c2aba86b9341","4138b533-381a-4239-82d8-b29aa402786c"]}
2017-07-06 23:17:27 INFO Selenium -> GET session/85c17f0b-e6aa-480a-a98e-92584475a54a/window_handles
2017-07-06 23:17:27 INFO Selenium <- {"sessionId":"85c17f0b-e6aa-480a-a98e-92584475a54a","status":0,"value":["a2658638-9fe8-425c-924a-c2aba86b9341","4138b533-381a-4239-82d8-b29aa402786c"]}
2017-07-06 23:17:27 INFO Selenium -> POST session/85c17f0b-e6aa-480a-a98e-92584475a54a/window
2017-07-06 23:17:27 INFO Selenium    >>> http://127.0.0.1:5555/session/85c17f0b-e6aa-480a-a98e-92584475a54a/window | {"name":"4138b533-381a-4239-82d8-b29aa402786c"}
Net::ReadTimeout: Net::ReadTimeout
from I:/Opt/Ruby/Ruby223x64/lib/ruby/2.3.0/net/protocol.rb:158:in `rbuf_fill'
[3] pry(#<Actions>)>
```

In Chrome, the new window is detected and `#use` is successful, but then `@browser.title` times out:

```
[1] pry(#<Actions>)> @browser.windows
2017-07-06 23:04:45 INFO Selenium -> GET session/7583314e7bb51b20c92bfb712e3728b3/window_handles
2017-07-06 23:04:45 INFO Selenium <- {"sessionId":"7583314e7bb51b20c92bfb712e3728b3","status":0,"value":["CDwindow-d7a461b7-093f-41e7-b47b-7ef620a4043b","CDwindow-0af13294-c5b4-4e6e-8de7-248cf5ce5e4a"]}
=> [
    [0] #<Watir::Window:0x911b2c48 located=true>,
    [1] #<Watir::Window:0x8921e770 located=true>
]
[2] pry(#<Actions>)> @browser.windows.last.use
2017-07-06 23:04:53 INFO Selenium -> GET session/7583314e7bb51b20c92bfb712e3728b3/window_handles
2017-07-06 23:04:53 INFO Selenium <- {"sessionId":"7583314e7bb51b20c92bfb712e3728b3","status":0,"value":["CDwindow-d7a461b7-093f-41e7-b47b-7ef620a4043b","CDwindow-0af13294-c5b4-4e6e-8de7-248cf5ce5e4a"]}
2017-07-06 23:04:53 INFO Selenium -> GET session/7583314e7bb51b20c92bfb712e3728b3/window_handles
2017-07-06 23:04:53 INFO Selenium <- {"sessionId":"7583314e7bb51b20c92bfb712e3728b3","status":0,"value":["CDwindow-d7a461b7-093f-41e7-b47b-7ef620a4043b","CDwindow-0af13294-c5b4-4e6e-8de7-248cf5ce5e4a"]}
2017-07-06 23:04:53 INFO Selenium -> POST session/7583314e7bb51b20c92bfb712e3728b3/window
2017-07-06 23:04:53 INFO Selenium    >>> http://127.0.0.1:9515/session/7583314e7bb51b20c92bfb712e3728b3/window | {"name":"CDwindow-0af13294-c5b4-4e6e-8de7-248cf5ce5e4a"}
2017-07-06 23:04:53 INFO Selenium <- {"sessionId":"7583314e7bb51b20c92bfb712e3728b3","status":0,"value":null}

=> #<Watir::Window:0x8921e770 located=true>
[3] pry(#<Actions>)> @browser.title
2017-07-06 23:04:57 INFO Selenium -> GET session/7583314e7bb51b20c92bfb712e3728b3/title
Net::ReadTimeout: Net::ReadTimeout
from I:/Opt/Ruby/Ruby223x64/lib/ruby/2.3.0/net/protocol.rb:158:in `rbuf_fill'
[4] pry(#<Actions>)>
```

Will try Firefox tomorrow and report back.

**Comment by titusfortner** [comment]
huh, well, it's weird that the return value wasn't logged before the next command was executed...

Regardless, this is a Selenium or driver issue and not a Watir issue.

Run this code and create an issue in Selenium project with the results. It might be worth doing this in Firefox (ideally Firefox Nightly with the most recent geckodriver), since that is attempting to be 100% w3c compliant.

```ruby
Selenium::WebDriver.logger.level = :info
driver = @browser.wd
current_window = driver.window_handle
new_window = driver.window_handles.find { |window| window != current_window }
driver.switch_to.window(new_window)
driver.title
```

If you want to discuss this in real time, you can join the [Selenium Slack](http://seleniumhq.herokuapp.com). There's also a relatively active #watir channel.

**Comment by kapoorlakshya** [comment]
Alrighty, thanks!
