### ISSUE TITLE
Newest Chrome throwing "Runtime.executionContextCreated has invalid 'context'" error

### ISSUE THREAD

**Issue by ryan-sherpa** [watir/watir#645]
I'm actual not completely sure this is related to the latest chrome, but when I initialize watir with the chrome browser I get the below stacktrace: 

```
script/filler_sandbox.rb:162: warning: duplicated key at line 175 ignored: :state
script/filler_sandbox.rb:234: warning: duplicated key at line 245 ignored: :state
/Users/ryan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/htmlentities-4.3.1/lib/htmlentities/mappings/expanded.rb:465: warning: duplicated key at line 466 ignored: "inodot"
/Users/ryan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/chef-11.12.8/lib/chef/data_bag_item.rb:161: warning: circular argument reference - data_bag
/Users/ryan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/actionpack-3.2.22.4/lib/action_dispatch/http/mime_type.rb:102: warning: already initialized constant Mime::PDF
/Users/ryan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/actionpack-3.2.22.4/lib/action_dispatch/http/mime_type.rb:102: warning: previous definition of PDF was here
/Users/ryan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok': session not created exception (Selenium::WebDriver::Error::SessionNotCreatedError)
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"83991.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=61.0.3163.79)
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.12.2 x86_64)
	from /Users/ryan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	from /Users/ryan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
	from /Users/ryan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
	from /Users/ryan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
	from /Users/ryan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
	from /Users/ryan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/bridge.rb:170:in `execute'
	from /Users/ryan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/bridge.rb:103:in `create_session'
	from /Users/ryan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/bridge.rb:54:in `handshake'
	from /Users/ryan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/chrome/driver.rb:57:in `initialize'
	from /Users/ryan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/common/driver.rb:46:in `new'
	from /Users/ryan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/common/driver.rb:46:in `for'
	from /Users/ryan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver.rb:86:in `for'
	from /Users/ryan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/watir-6.7.3/lib/watir/browser.rb:48:in `initialize'
```

**Comment by titusfortner** [comment]
You are using a rather old version of chromedriver.
You can use `webdrivers.gem` to keep them updated automatically.

**Comment by ryan-sherpa** [comment]
Greatly appreciate the feedback, mate. 🙏

**Comment by titusfortner** [comment]
If I had a nickel for every issue/question based on an outdated driver... :-)
