### ISSUE TITLE
Wait_Until does not wait, returns 404 for non existing element

### ISSUE THREAD

**Issue by gavk34** [watir/watir#655]
## Meta -
Watir Version: 6.8.4
Selenium Version: 3.5.2
Browser Version: firefox-56.0b3
Browser Driver Version: geckodriver-v0.18.0-linux64
OS Version: 10.10.5 OS X Yosemite

## Expected Behavior -
Waits for element to be present

## Actual Behavior -
Returns 404 instantly - no wait is observed

## Steps to reproduce -
b = Watir::Browser.new :firefox
b.goto 'www.google.com'
b.button(:id => 'test').wait_until(&:present?)
b.button(:id => 'test').wait_until(&:exist?)

```
irb(main):014:0> b.button(:id => 'test').wait_until(&:present?)
Selenium::WebDriver::Error::ServerError: status code 404
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/response.rb:74:in `assert_ok'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/bridge.rb:170:in `execute'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/w3c/bridge.rb:537:in `execute'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/remote/w3c/bridge.rb:517:in `find_element_by'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/common/search_context.rb:62:in `find_element'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/watir-6.8.4/lib/watir/locators/element/locator.rb:266:in `locate_element'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/watir-6.8.4/lib/watir/locators/element/locator.rb:72:in `by_id'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/watir-6.8.4/lib/watir/locators/element/locator.rb:39:in `locate'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/watir-6.8.4/lib/watir/elements/element.rb:592:in `locate'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/watir-6.8.4/lib/watir/elements/element.rb:574:in `assert_exists'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/watir-6.8.4/lib/watir/elements/element.rb:50:in `exists?'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/watir-6.8.4/lib/watir/wait.rb:46:in `block in until'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/watir-6.8.4/lib/watir/wait.rb:89:in `block in run_with_timer'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/watir-6.8.4/lib/watir/wait/timer.rb:20:in `block in wait'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/watir-6.8.4/lib/watir/wait/timer.rb:19:in `loop'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/watir-6.8.4/lib/watir/wait/timer.rb:19:in `wait'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/watir-6.8.4/lib/watir/wait.rb:88:in `run_with_timer'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/watir-6.8.4/lib/watir/wait.rb:45:in `until'
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/watir-6.8.4/lib/watir/wait.rb:125:in `wait_until'
	from (irb):14
	from /Users/gkelly/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
```

**Comment by titusfortner** [comment]
It appears the page didn't load. The element will never appear if the page doesn't load properly.

**Comment by gavk34** [comment]
It seems the page has loaded though, if I try to locate an element that is actually on the page I get the below response. However the reported error only occurs for elements that are not present, it returns 404 instantly instead of waiting for the element to become present

```
b.input(:value => 'Google Search').wait_until(&:present?)
=> #<Watir::Input: located: true; {:value=>"Google Search", :tag_name=>"input"}>
```

**Comment by titusfortner** [comment]
I can try to duplicate later, but can you run with logging?

`Selenium:: WebDriver.logger.level = :debug`

**Comment by gavk34** [comment]
Thanks @titusfortner , see below for debug log output. No rush...appreciate the assistance :)

```
2017-09-22 15:44:53 INFO Selenium -> POST session/174fe6fc-c57d-4b41-96fd-75c1d870a19a/element
2017-09-22 15:44:53 INFO Selenium    >>> http://127.0.0.1:4444/session/174fe6fc-c57d-4b41-96fd-75c1d870a19a/element | {"using":"xpath","value":".//input[@value='test']"}
2017-09-22 15:44:53 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"51"}
2017-09-22 15:44:53 INFO Selenium <- {"error":"no such element","message":"Unable to locate element: .//input[@value='test']"}
Selenium::WebDriver::Error::ServerError: status code 404
```

**Comment by titusfortner** [comment]
Huh, yeah, geckodriver shouldn't be throwing that error. I'll look into it later

**Comment by gavk34** [comment]
Sorry, think I have solved the problem, I was using the linux driver by accident on my MAC. Seems to work ok if I use the macos driver. Closing

**Comment by titusfortner** [comment]
Hah! I have actually done that before myself. I'm glad you got it figured out.
