### ISSUE TITLE
Problem run watir on MacOs High Sierra

### ISSUE THREAD

**Issue by alefhsousa** [watir/watir#716]
## Meta -
Watir Version: 6.10.3
Selenium Version: 
Browser Version:  67.0
Browser Driver Version: 2.37.544337 (8c0344a12e552148c185f7d5117db1f28d6c9e85)
OS Version: High Sierra 10.13.3

## Expected Behavior -

Run the sample code of watir:

```ruby
require 'watir'
require 'webdrivers'


b = Watir::Browser.new 

browser = Watir::Browser.new 

browser.goto 'watir.com'
browser.link(text: 'documentation').click

puts browser.title
# => 'Documentation – Watir Project...'
browser.close
```

## Actual Behavior -
Returned an `UnknownError`

```
/Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok': unknown error: cannot find Chrome binary (Selenium::WebDriver::Error::UnknownError)
  (Driver info: chromedriver=2.37.544337 (8c0344a12e552148c185f7d5117db1f28d6c9e85),platform=Mac OS X 10.13.3 x86_64)
	from /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
	from /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
	from /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/bridge.rb:97:in `create_session'
	from /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/bridge.rb:53:in `handshake'
	from /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/chrome/driver.rb:47:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/common/driver.rb:44:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/common/driver.rb:44:in `for'
	from /Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver.rb:85:in `for'
	from /Library/Ruby/Gems/2.3.0/gems/watir-6.10.3/lib/watir/browser.rb:48:in `initialize'
	from simple.rb:5:in `new'
	from simple.rb:5:in `<main>'
```

## Steps to reproduce -

Create a simple project with dependencies on `Gemfile`:

```
source 'https://rubygems.org'

group :test do
  gem 'cucumber', '1.2.1'
  gem 'watir-webdriver', '0.7.0'
  gem 'watir'
  gem 'selenium-webdriver'
  gem 'headless', '0.2.2'
  gem "webdrivers", "~> 3.0"
end
````

Run bundle install 

try execute code: 

``` 
require 'watir'
require 'webdrivers'


b = Watir::Browser.new 

browser = Watir::Browser.new :safari

browser.goto 'watir.com'
browser.link(text: 'documentation').click

puts browser.title
# => 'Documentation – Watir Project...'
browser.close

```

**Comment by titusfortner** [comment]
Please remove `watir-webdriver` from your list of gems, and make sure you have `gem 'watir', '~> 6.0'`
You can also remove the `headless` gem as it is incompatible with Safari.
I know this sounds obvious, but please make sure that you do in fact have Chrome installed on the system, since it is not installed by default.
If you have Chrome installed and once you've fixed the gems you are still seeing this error, you can specify the location of Chrome by using: `Selenium::WebDriver::Chrome.path = 'path/to/binary'`

**Comment by titusfortner** [comment]
@alefhsousa were you able to get this to work? Let me know if you're still having issues and I'll reopen.
