### ISSUE TITLE
No longer able to wait for re-created element to become present

### ISSUE THREAD

**Issue by jkotests** [watir/watir#730]
## Meta -
Watir Version: 6.11.0.beta1, 6.11.0.beta2 (problem does not occur in 6.10.3)
Selenium Version: 3.12.0
Browser Version: 66.0.3359.139
Browser Driver Version: 2.38
OS Version: Windows 10

## Expected Behavior -

I have an element that:
* Initially exists in the DOM, but is hidden
* Is re-created before being displayed

I would expect to be able to wait for the element to become present by using `#wait_until_present`.

## Actual Behavior -

Watir behaved as expected in 6.10.3. However, as of 6.11.0.beta, this no longer works. A timeout will now occur.

## Steps to reproduce -

Given the HTML file (modified from wait.html):

~~~~~~~~html
<!DOCTYPE HTML>
<html>
  <head>
    <title>wait test</title>
    <script type="text/javascript" charset="utf-8">

      function setTimeoutAddDisplay(id, current_id, timeout) {
          setTimeoutAdd(id, "none", id, current_id, timeout);
          setTimeoutDisplay(id, "block", timeout*2)
      }

      function setTimeoutDisplay(id, display, timeout) {
          setTimeout(function() {
              document.getElementById(id).style.display = display;
          }, timeout);
      }

      function setTimeoutAdd(id, display, text, existing_id, timeout) {
          var newDiv = document.createElement("div");
          newDiv.setAttribute("id", id);
          newDiv.style.display = display;
          newDiv.appendChild(document.createTextNode(text));

          var currentDiv = document.getElementById(existing_id);

          setTimeout(function() {
              document.body.insertBefore(newDiv, currentDiv);
          }, timeout);
      }

      function setTimeoutRemove(id, timeout) {
          setTimeout(function() {
              var e = document.getElementById(id);
              e.parentNode.removeChild(e);
          }, timeout);
      }
    </script>
  </head>

  <body>
    <div id="foo" style="display:block;">foo</div>
    <div id="bar" style="display:none;" onclick='this.innerHTML = "changed"'>bar</div>
    <a id="readd_bar" href="#" onclick="setTimeoutRemove('bar', 1000); setTimeoutAddDisplay('bar', 'foo', 2000);">re-add bar</a>
  </body>
</html>
~~~~~~~~

The following code will now timeout:

~~~~~~~~ruby
browser = Watir::Browser.new :chrome
browser.goto File.join(__dir__, 'test.htm')
browser.link(id: 'readd_bar').click # removes, re-adds and then displays element
browser.div(id: 'bar').wait_until_present
#=> C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.11.0.beta2/lib/watir/wait.rb:49:in `until': timed out after 30 seconds, waiting for true condition on #<Watir::Div: located: false; {:id=>"bar", :tag_name=>"div"}> (Watir::Wait::TimeoutError)
#=> 	from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.11.0.beta2/lib/watir/wait.rb:125:in `wait_until'
#=> 	from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.11.0.beta2/lib/watir/wait.rb:173:in `wait_until_present'
#=> 	from test.rb:16:in `<main>'
~~~~~~~~

**Comment by titusfortner** [comment]
Sigh. This is a non-trivial regression. I'll keep digging into it; I do want this fixed before releasing 6.11
