### ISSUE TITLE
 (Errno::EALREADY) Operation already in progress - when running

### ISSUE THREAD

**Issue by c0ze** [watir/watir#792]
## Meta -
Watir Version: 6.8.4
Selenium Version: 3.4.1 (gem) 3.14.0 (server)
Browser Version: ~
Browser Driver Version: chromium-driver 69.0.3497.92-1~deb9u1
OS Version: Windows 10 WLS debian (but I also have the same issue in MacOS)

## Expected Behavior -

watir running

## Actual Behavior -

watir not running

## Steps to reproduce -

Install watir gem.
Install selenium-server
run selenium server
Copy paste example code from starting guide

```
require 'watir'

browser = Watir::Browser.new

browser.goto 'watir.com'
browser.link(text: 'Guides').click

puts browser.title
# => 'Guides – Watir Project'
browser.close
```

execute the code
I get

```
        14: from /home/arda/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/watir-6.8.4/lib/watir/browser.rb:48:in `initialize'
        13: from /home/arda/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver.rb:84:in `for'
        12: from /home/arda/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/common/driver.rb:44:in `for'
        11: from /home/arda/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/common/driver.rb:44:in `new'
        10: from /home/arda/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/chrome/driver.rb:51:in `initialize'
         9: from /home/arda/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/common/service.rb:69:in `start'
         8: from /home/arda/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/common/socket_lock.rb:39:in `locked'
         7: from /home/arda/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/common/service.rb:72:in `block in start'
         6: from /home/arda/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/common/service.rb:141:in `connect_until_stable'
         5: from /home/arda/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/common/socket_poller.rb:39:in `connected?'
         4: from /home/arda/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/common/socket_poller.rb:100:in `with_timeout'
         3: from /home/arda/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/common/socket_poller.rb:39:in `block in connected?'
         2: from /home/arda/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/common/socket_poller.rb:79:in `listening?'
         1: from /home/arda/.rbenv/versions/2.5.1/lib/ruby/2.5.0/socket.rb:1213:in `connect_nonblock'
/home/arda/.rbenv/versions/2.5.1/lib/ruby/2.5.0/socket.rb:1213:in `__connect_nonblock': Operation already in progress - connect(2) for 127.0.0.1:9515 (Errno::EALREADY)
```

**Comment by titusfortner** [comment]
This is a Selenium issue, not a Watir issue, and it looks like it was updated in master, but not yet released: https://github.com/SeleniumHQ/selenium/issues/6213
