### ISSUE TITLE
Locators with hyphens and conditional regexps are not working on watir 6.15

### ISSUE THREAD

**Issue by danielfsbarreto** [watir/watir#824]
## Meta -
Watir Version: 6.15
Selenium Version: 3.141.0
Browser Version: 70.0.3538.77 (Official Build) (64-bit)
Browser Driver Version: ChromeDriver 2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706)
OS Version: Ubuntu 18.04.1 LTS

## Expected Behavior -
Locators containing hyphens and conditionals like `row.divs(class: /(task-description|is-task_description)/).find(&:present?)` should work just fine, as it is composed by an absolutely valid regular expression. This snippet behaves as expected on 6.14.

## Actual Behavior -
```ruby
row.divs(class: /(task-description|is-task_description)/).find(&:present?)
```
```
RegexpError: empty range in char class: /[\/(task-description|is-task_description)\/]/
from /home/danielfsbarreto/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/watir-6.15.0/lib/watir/locators/element/locator.rb:171:in `block in matches_values?'
```

## Steps to reproduce -
```ruby
gem 'watir', '=6.15'
require 'watir'

browser = Watir::Browser.new
browser.goto 'https://jsfiddle.net/hx0tp3jg/'
browser.iframe(name: 'result').div(class: /(task-description|is-task_description)/).text
```
```
Traceback (most recent call last):
       16: from /home/danielfsbarreto/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/watir-6.15.0/lib/watir/elements/element.rb:603:in `locate'
       15: from /home/danielfsbarreto/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/watir-6.15.0/lib/watir/elements/element.rb:715:in `locate_in_context'
       14: from /home/danielfsbarreto/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/watir-6.15.0/lib/watir/locators/element/locator.rb:27:in `locate'
       13: from /home/danielfsbarreto/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/watir-6.15.0/lib/watir/locators/element/locator.rb:67:in `using_watir'
       12: from /home/danielfsbarreto/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/watir-6.15.0/lib/watir/locators/element/locator.rb:204:in `locate_matching_elements'
       11: from /home/danielfsbarreto/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/watir-6.15.0/lib/watir/locators/element/locator.rb:112:in `matching_elements'
       10: from /home/danielfsbarreto/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/watir-6.15.0/lib/watir/locators/element/locator.rb:112:in `to_a'
        9: from /home/danielfsbarreto/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/watir-6.15.0/lib/watir/locators/element/locator.rb:112:in `each'
        8: from /home/danielfsbarreto/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/watir-6.15.0/lib/watir/locators/element/locator.rb:112:in `each'
        7: from /home/danielfsbarreto/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/watir-6.15.0/lib/watir/locators/element/locator.rb:112:in `each'
        6: from /home/danielfsbarreto/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/watir-6.15.0/lib/watir/locators/element/locator.rb:112:in `each'
        5: from /home/danielfsbarreto/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/watir-6.15.0/lib/watir/locators/element/locator.rb:109:in `block in matching_elements'
        4: from /home/danielfsbarreto/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/watir-6.15.0/lib/watir/locators/element/locator.rb:166:in `matches_values?'
        3: from /home/danielfsbarreto/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/watir-6.15.0/lib/watir/locators/element/locator.rb:166:in `all?'
        2: from /home/danielfsbarreto/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/watir-6.15.0/lib/watir/locators/element/locator.rb:166:in `each'
        1: from /home/danielfsbarreto/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/watir-6.15.0/lib/watir/locators/element/locator.rb:171:in `block in matches_values?'
RegexpError (empty range in char class: /[\/(task-description|is-task_description)\/]/)
```

**Comment by titusfortner** [comment]
Thanks for the thorough report, I can reproduce it. Something to do with how we are putting classes into Arrays for processing; I'll have to track down what's different in the 6.15 implementation.

Also, for reference, these will do the same thing; the second might be easier to read.
```
row.divs(class: /(task-description|is-task_description)/).find(&:present?)
row.div(class: /(task-description|is-task_description)/, visible: true)
```

**Comment by danielfsbarreto** [comment]
I am happy to help! Thanks for your suggestion, the 2nd option seems better indeed.

**Comment by jkotests** [comment]
@titusfortner , I think the problem is in [`Locator#matches_values?`](https://github.com/watir/watir/blob/bfa47ac17d2131d64a1c994bf739e2c5448c3b58/lib/watir/locators/element/locator.rb#L165-L173) , which compares the class attribute via:

~~~~~~~~
what == val || val =~ /#{what}/
~~~~~~~~

We don't properly handle the `what` being an Array. Dropping it directly into the Regexp results in:
* Comparing val to a character character class (ie we are going to be matching a lot more than expected) or
* Creating invalid Regexps that result in the reported exception.

This isn't specific to 6.15. The problem will occur in 6.14 if the :class is manually specified as an Array:

~~~~~~~~
# In 6.14:
browser.div(class: [/(task-description|is-task_description)/]).present?
#=> TypeError: no implicit conversion of Regexp into String
~~~~~~~~

The problem has become more evident in 6.15 due to SelectorBuilder always returning the :class filter as an Array.

**Comment by titusfortner** [comment]
Yeah, the solution was easy. Figuring out the correct place to put the spec led me down a rabbit hole of majorly refactoring the locator code to allow better unit testing for it. #excitingThanksgiving

**Comment by titusfortner** [comment]
This was fixed with #825

**Comment by danielfsbarreto** [comment]
@titusfortner, what version may include this fix? 6.16? BTW, thanks for jumping on it so quickly!

**Comment by titusfortner** [comment]
Yes, should get it released this weekend.

**Comment by danielfsbarreto** [comment]
Terrific!
