### ISSUE TITLE
Can't upload file in Firefox 

### ISSUE THREAD

**Issue by peacebytes** [watir/watir#855]
## Meta -
Watir Version: 6.16.5
Selenium Version: 3.141.0
Browser Version: Firefox 61 (64-bit)
Browser Driver Version: geckodriver-v0.24.0-linux64.
OS Version: Ubuntu 18.04

## Expected Behavior -
Firefox should allow to upload local files with absolute path
## Actual Behavior -
Error occured:
```
element located, but timed out after 30 seconds, waiting for #<Watir::FileField: located: true; 
{:tag_name=>"input", :type=>"file"}> to be present (Watir::Exception::UnknownObjectException)
```
## Steps to reproduce -
Trying to upload with code
```
file_name = "#{File.expand_path('.')}/inventory/uploadtest/photo1.jpg"
Watir.relaxed_locate = false
@browser.file_field.send_keys file_name
Watir.relaxed_locate = true
```
Stack trace
```
["/var/lib/gems/2.5.0/gems/watir-6.16.5/lib/watir/elements/element.rb:752:in `raise_present'", 
"/var/lib/gems/2.5.0/gems/watir-6.16.5/lib/watir/elements/element.rb:803:in `rescue in element_call'", 
"/var/lib/gems/2.5.0/gems/watir-6.16.5/lib/watir/elements/element.rb:787:in `element_call'", 
"/var/lib/gems/2.5.0/gems/watir-6.16.5/lib/watir/elements/element.rb:338:in `send_keys'", 
"/home/{personal_folder}/features/step_definitions/uploadpopup_steps.rb:45:in `block in <top 
(required)>'", "/var/lib/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/glue/invoke_in_world.rb:39:in 
`instance_exec'", "/var/lib/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/glue/invoke_in_world.rb:39:in 
`block in cucumber_instance_exec_in'", "/var/lib/gems/2.5.0/gems/cucumber-
3.1.2/lib/cucumber/glue/invoke_in_world.rb:54:in `cucumber_run_with_backtrace_filtering'", 
"/var/lib/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/glue/invoke_in_world.rb:27:in 
`cucumber_instance_exec_in'", "/var/lib/gems/2.5.0/gems/cucumber-
....
```

Tried with `set file_name`
```
Watir.relaxed_locate = false
@browser.file_field.set file_name
 Watir.relaxed_locate = true
```
Stacktrace
```
["/var/lib/gems/2.5.0/gems/watir-6.16.5/lib/watir/elements/element.rb:752:in `raise_present'", 
"/var/lib/gems/2.5.0/gems/watir-6.16.5/lib/watir/elements/element.rb:804:in `rescue in element_call'", 
"/var/lib/gems/2.5.0/gems/watir-6.16.5/lib/watir/elements/element.rb:787:in `element_call'", 
"/var/lib/gems/2.5.0/gems/watir-6.16.5/lib/watir/elements/file_field.rb:24:in `value='", 
"/var/lib/gems/2.5.0/gems/watir-6.16.5/lib/watir/elements/file_field.rb:13:in `set'"

```
Everything works just fine on Chrome.

Please help if you have any ideas. I was looking at https://github.com/watir/watir/issues/497 but seems someone had issues on Chrome eventually.

**Comment by titusfortner** [comment]
Ah, ok, so, by default an `#send_keys` requires that an element be displayed before taking action. `FileField#set` does not force an element to be displayed in order to do an upload.

Please don't do anything with relaxed_locate, it will be going away soon.

What you want to use is:
```
@browser.file_field.set file_name
```

**Comment by peacebytes** [comment]
Browser Version: Firefox 61 (64-bit)
Browser Driver Version: geckodriver-v0.24.0-linux64.
OS Version: Ubuntu 18.04

I still see this error on Firefox when using `@browser.file_field.set file_name`

```
element located, but timed out after 30 seconds, waiting for #<Watir::FileField: located: true; {:tag_name=>"input", :type=>"file"}> to be present (Watir::Exception::UnknownObjectException
```
