### ISSUE TITLE
Element is located, but cannot be clicked

### ISSUE THREAD

**Issue by mjacobus** [watir/watir#864]
### Dev env
Watir Version: 6.16.5
Selenium Version: selenium-webdriver 3.141.0
Browser Version: Version 73.0.3683.103 (Official Build) (64-bit)
Browser Driver Version: 2.46.628388 
ChromeDriver 73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72)
OS Version: Mac OS 10.14.4

### Circle CI
Watir Version: 6.16.5
Selenium Version: selenium-webdriver 3.141.0
Browser Version: 73.0.3683.103
Browser Driver Version: ChromeDriver 73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72)
OS Version: Linux 4.4.0-144-generic x86_64

## Expected Behavior -

Element is clicked

## Actual Behavior -

Element is visible, but cannot be clicked for some reason.

## Steps to reproduce -

Html:

```html
<div class="css-1yv5pu4">
  <a type="button" class="css-r6eevn">
    <svg viewBox="0 0 22 22" class="css-1qpgiio" width="18" height="18" preserveAspectRatio="xMidYMid meet" style="transform: scaleX(-1);">
      <path d="M11 19.25a1.376 1.376 0 0 0 0-2.75H1.375a1.376 1.376 0 0 0 0 2.75H11zM20.625 5.5a1.376 1.376 0 0 0 0-2.75H1.375a1.376 1.376 0 0 0 0 2.75h19.25zm0 6.875a1.376 1.376 0 0 0 0-2.75H1.375a1.376 1.376 0 0 0 0 2.75h19.25z">
      </path>
    </svg>
    <div class="css-9paxos">
      <h5 class="css-1youhy2">UN</h5>
    </div>
  </a>
</div>
```

```ruby
 browser.h5(text: 'UN').click
```

```Failure/Error: browser.h5(text: 'UN').click

Watir::Exception::UnknownObjectException:
  element located, but timed out after 30 seconds, waiting for #<Watir::Heading: located: true; {:text=>"UN", :tag_name=>"h5"}> to be present
./spec/acceptance/support/pages/cms/profile_settings/page.rb:17:in `open_profile_settings'
./spec/acceptance/cms/profile_settings_spec.rb:20:in `block (3 levels) in <main>'
./spec/support/watir_acceptance_helper.rb:60:in `block in on_page'
./spec/support/watir_acceptance_helper.rb:58:in `tap'
./spec/support/watir_acceptance_helper.rb:58:in `on_page'
./spec/acceptance/cms/profile_settings_spec.rb:16:in `block (2 levels) in <main>'
./spec/rails_helper.rb:93:in `block (2 levels) in <top (required)>'
------------------
--- Caused by: ---
Selenium::WebDriver::Error::ElementNotVisibleError:
  element not interactable
    (Session info: headless chrome=73.0.3683.103)
    (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-144-generic x86_64)
  ./spec/acceptance/support/pages/cms/profile_settings/page.rb:17:in `open_profile_settings'
```

Circle CI fails every time. Dev env, fails 1 out of 10.

**Comment by mjacobus** [comment]
Nevermind. The error on dev machine was slightly different.

On CircleCi though, with headless, i got the error above, and the problem was window size, fixed with:

```ruby
browser.window.resize_to(1280, 1024)
```
