### ISSUE TITLE
Chrome - screenshot.save produced "Exception: timeout: Timed out receiving message from renderer"

### ISSUE THREAD

**Issue by diggde** [watir/watir#872]
## Meta -
Watir Version: 6.16.5
Browser Version: Chrome 75.0.3770.100
Browser Driver Version: 75.0.3770.90
OS Version: Ubuntu 16.04 LTS

## Expected Behavior -
Save a screenshot to file

## Actual Behavior -
Don't save a screenshot, produced error-message:

```
#0 0x557d043886e9 <unknown>: timeout: Timed out receiving message from renderer: 9,999 (Selenium::WebDriver::Error::TimeoutError)
  (Session info: chrome=75.0.3770.100)
	from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok'
	from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
	from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/http/common.rb:88:in `new'
	from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
	from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/http/default.rb:114:in `request'
	from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
	from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
	from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/w3c/bridge.rb:567:in `execute'
	from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/w3c/bridge.rb:229:in `screenshot'
	from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/common/driver_extensions/takes_screenshot.rb:56:in `screenshot_as'
	from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/common/driver_extensions/takes_screenshot.rb:40:in `block in save_screenshot'
	from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/common/driver_extensions/takes_screenshot.rb:40:in `open'
	from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/common/driver_extensions/takes_screenshot.rb:40:in `save_screenshot'
	from /var/lib/gems/2.3.0/gems/watir-6.16.5/lib/watir/screenshot.rb:24:in `save'
	from test.rb:5:in `<main>'
```

## Steps to reproduce -
Code Example:

```
require "rubygems"
require "watir"
browser = Watir::Browser.new :chrome
browser.goto 'http://watir.com/'
browser.screenshot.save 'screenshot.png'
```

**Comment by diggde** [comment]
Solved: using of switch `--disable-gpu` fix the problem
