### ISSUE TITLE
Chrome failed to start: exited normally.

### ISSUE THREAD

**Issue by christianbaumann** [watir/watir#971]
## Meta -
selenium-webdriver 4.8.6
watir 7.2.2
webdrivers 5.2.0
Browser Version: 112.0.5615.138
Browser Driver Version: ?
OS Version: Windows 11 Pro 22H2 22621.1555

## Expected Behavior -
`browser = Watir::Browser.new` starts Chrome in new window, executes the rest of the script

## Actual Behavior -
`browser = Watir::Browser.new` starts new tab in open Chrome, scripts aborts with error message:

```
2023-05-02 11:34:42 WARN Selenium [:logger_info] Details on how to use and modify Selenium logger:
  https://selenium.dev/documentation/webdriver/troubleshooting/logging#ruby

2023-05-02 11:34:42 WARN Selenium applicable driver not found; attempting to install with Selenium Manager
Wird in einer aktuellen Browsersitzung ge÷ffnet.
Backtrace:: unknown error: Chrome failed to start: exited normally. (Selenium::WebDriver::Error::UnknownError)
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
        from    GetHandleVerifier [0x00DADCE3+50899]
        from    (No symbol) [0x00D3E111]
        from    (No symbol) [0x00C45588]
        from    (No symbol) [0x00C6281C]
        from    (No symbol) [0x00C5F479]
        from    (No symbol) [0x00C91FFE]
        from    (No symbol) [0x00C91CEC]
        from    (No symbol) [0x00C8B6F6]
        from    (No symbol) [0x00C67708]
        from    (No symbol) [0x00C6886D]
        from    GetHandleVerifier [0x01013EAE+2566302]
        from    GetHandleVerifier [0x010492B1+2784417]
        from    GetHandleVerifier [0x0104327C+2759788]
        from    GetHandleVerifier [0x00E45740+672048]
        from    (No symbol) [0x00D48872]
        from    (No symbol) [0x00D441C8]
        from    (No symbol) [0x00D442AB]
        from    (No symbol) [0x00D371B7]
        from    BaseThreadInitThunk [0x75627D49+25]
        from    RtlInitializeExceptionChain [0x7710B74B+107]
        from    RtlClearBits [0x7710B6CF+191]
        from C:/tools/Ruby32-x64/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.6/lib/selenium/webdriver/remote/response.rb:55:in `assert_ok'
        from C:/tools/Ruby32-x64/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.6/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
        from C:/tools/Ruby32-x64/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.6/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
        from C:/tools/Ruby32-x64/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.6/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
        from C:/tools/Ruby32-x64/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.6/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
        from C:/tools/Ruby32-x64/lib/ruby/gems/3.2.0/gems/watir-7.2.2/lib/watir/http_client.rb:8:in `request'
        from C:/tools/Ruby32-x64/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.6/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
        from C:/tools/Ruby32-x64/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.6/lib/selenium/webdriver/remote/bridge.rb:619:in `execute'
        from C:/tools/Ruby32-x64/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.6/lib/selenium/webdriver/remote/bridge.rb:53:in `create_session'
        from C:/tools/Ruby32-x64/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.6/lib/selenium/webdriver/common/driver.rb:317:in `block in create_bridge'
        from <internal:kernel>:90:in `tap'
        from C:/tools/Ruby32-x64/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.6/lib/selenium/webdriver/common/driver.rb:316:in `create_bridge'
        from C:/tools/Ruby32-x64/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.6/lib/selenium/webdriver/common/driver.rb:74:in `initialize'
        from C:/tools/Ruby32-x64/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.6/lib/selenium/webdriver/chrome/driver.rb:35:in `initialize'
        from C:/tools/Ruby32-x64/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.6/lib/selenium/webdriver/common/driver.rb:47:in `new'
        from C:/tools/Ruby32-x64/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.6/lib/selenium/webdriver/common/driver.rb:47:in `for'
        from C:/tools/Ruby32-x64/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.8.6/lib/selenium/webdriver.rb:88:in `for'
        from C:/tools/Ruby32-x64/lib/ruby/gems/3.2.0/gems/watir-7.2.2/lib/watir/browser.rb:46:in `initialize'
        from C:/git_repos/_own/ruby-misc/create_outlook_pomodoro_appointment/create_outlook_pomodoro_appointment.rb:53:in `new'
        from C:/git_repos/_own/ruby-misc/create_outlook_pomodoro_appointment/create_outlook_pomodoro_appointment.rb:53:in `start_pomodoro_timer'
        from C:/git_repos/_own/ruby-misc/create_outlook_pomodoro_appointment/create_outlook_pomodoro_appointment.rb:64:in `<main>'
```

## Steps to reproduce -
Execute `browser = Watir::Browser.new`

## Hint
Might be related to https://github.com/SeleniumHQ/selenium/issues/11884

**Comment by titusfortner** [comment]
Sorry for the late reply, this should be fixed in latest Selenium. Thanks.
